-- AlterTable
ALTER TABLE "User" ADD COLUMN "freeGen1" TIMESTAMP(3),
ADD COLUMN "freeGen2" TIMESTAMP(3),
ADD COLUMN "premiumCount" INTEGER NOT NULL DEFAULT 0,
ADD COLUMN "premiumLastGen" TIMESTAMP(3);
